import type { Rental, MarketplaceItem, ForumPost, Event, LostFoundItem, Service, TutoringListing, Announcement } from '@/shared/types';

// ============================================
// Mock Rentals (Alquileres cerca de UNLAR)
// ============================================
export const mockRentals: Partial<Rental>[] = [
  {
    id: 'mock-rental-1',
    title: 'Depto 2 ambientes a 3 cuadras de UNLAR',
    description: 'Departamento luminoso con balcón, ideal para estudiantes. Incluye expensas. Zona tranquila cerca de Av. Ortiz de Ocampo.',
    type: 'apartment',
    price: 180000,
    currency: 'ARS',
    location: 'Av. Ortiz de Ocampo 1450',
    neighborhood: 'Centro',
    amenities: ['WiFi', 'Cocina', 'Lavarropas', 'Balcón'],
    image_urls: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400'],
    available_from: '2025-03-01',
    allows_pets: false,
    gender_preference: 'any',
    status: 'active',
    created_at: '2025-01-15T10:00:00Z',
    view_count: 45,
    favorite_count: 12,
  },
  {
    id: 'mock-rental-2',
    title: 'Habitación en depto compartido - Solo chicas',
    description: 'Habitación privada en departamento compartido con otra estudiante. Gastos incluidos. A 5 min caminando de la facu.',
    type: 'room',
    price: 95000,
    currency: 'ARS',
    location: 'Calle Pelagio B. Luna 320',
    neighborhood: 'Barrio Residencial',
    amenities: ['WiFi', 'Cocina compartida', 'Patio'],
    image_urls: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400'],
    available_from: '2025-02-15',
    allows_pets: false,
    gender_preference: 'female',
    status: 'active',
    created_at: '2025-01-18T14:30:00Z',
    view_count: 32,
    favorite_count: 8,
  },
  {
    id: 'mock-rental-3',
    title: 'Monoambiente amoblado frente a Ciudad Universitaria',
    description: 'Monoambiente completamente amoblado, con aire acondicionado y heladera. Ideal para ingresantes. Contrato flexible.',
    type: 'apartment',
    price: 150000,
    currency: 'ARS',
    location: 'Av. Dr. René Favaloro 800',
    neighborhood: 'Ciudad Universitaria',
    amenities: ['Amoblado', 'Aire acondicionado', 'Heladera', 'WiFi'],
    image_urls: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400'],
    available_from: null,
    allows_pets: true,
    gender_preference: 'any',
    status: 'active',
    created_at: '2025-01-20T09:15:00Z',
    view_count: 67,
    favorite_count: 23,
  },
  {
    id: 'mock-rental-4',
    title: 'Depto compartido - Busco compañero/a',
    description: 'Somos 2 estudiantes de Ingeniería buscando un/a tercero/a. Depto grande, 3 habitaciones, living amplio. Dividimos gastos.',
    type: 'shared',
    price: 75000,
    currency: 'ARS',
    location: 'Calle San Nicolás de Bari 550',
    neighborhood: 'Barrio Norte',
    amenities: ['WiFi', 'Cocina', 'Living', 'Garage'],
    image_urls: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400'],
    available_from: '2025-03-10',
    allows_pets: true,
    gender_preference: 'any',
    status: 'active',
    created_at: '2025-01-22T16:45:00Z',
    view_count: 28,
    favorite_count: 5,
  },
];

// ============================================
// Mock Marketplace Items (Compra/Venta)
// ============================================
export const mockMarketplaceItems: Partial<MarketplaceItem>[] = [
  {
    id: 'mock-market-1',
    title: 'Calculadora Científica Casio fx-991ES',
    description: 'Calculadora en excelente estado, la usé solo 1 cuatrimestre para Análisis Matemático. Viene con funda.',
    category: 'electronics',
    price: 25000,
    condition: 'like_new',
    is_free: false,
    image_urls: ['https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=400'],
    status: 'active',
    created_at: '2025-01-19T11:00:00Z',
    view_count: 18,
    favorite_count: 4,
  },
  {
    id: 'mock-market-2',
    title: 'Apuntes completos de Derecho Civil I',
    description: 'Apuntes impresos y anillados del Prof. García, incluye resúmenes y casos prácticos. Todo el programa 2024.',
    category: 'notes',
    price: 5000,
    condition: 'good',
    is_free: false,
    image_urls: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400'],
    status: 'active',
    created_at: '2025-01-20T08:30:00Z',
    view_count: 34,
    favorite_count: 11,
  },
  {
    id: 'mock-market-3',
    title: 'Notebook Lenovo IdeaPad 3 - Impecable',
    description: 'Lenovo IdeaPad 3, i5 11va gen, 8GB RAM, 256GB SSD. Batería dura 5hs. Ideal para programar o estudiar.',
    category: 'electronics',
    price: 450000,
    condition: 'good',
    is_free: false,
    image_urls: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'],
    status: 'active',
    created_at: '2025-01-21T15:20:00Z',
    view_count: 56,
    favorite_count: 19,
  },
  {
    id: 'mock-market-4',
    title: 'Libros de Anatomía - REGALO',
    description: 'Ya me recibí y regalo mis libros de Anatomía de Rouvière (3 tomos). Retiro por Ciudad Universitaria.',
    category: 'books',
    price: null,
    condition: 'fair',
    is_free: true,
    image_urls: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400'],
    status: 'active',
    created_at: '2025-01-22T10:00:00Z',
    view_count: 89,
    favorite_count: 31,
  },
];

// ============================================
// Mock Forum Posts (Foro)
// ============================================
export const mockForumPosts: Partial<ForumPost>[] = [
  {
    id: 'mock-forum-1',
    title: '¿Alguien cursó Álgebra con el Prof. Martínez?',
    description: 'Estoy por anotarme en la comisión de la mañana. ¿Cómo es el parcial? ¿Toma mucha teoría o es más práctico?',
    category: 'question',
    tags: ['álgebra', 'ingeniería', 'parciales'],
    upvotes: 15,
    downvotes: 1,
    comment_count: 8,
    is_answered: true,
    status: 'active',
    created_at: '2025-01-18T20:00:00Z',
    view_count: 120,
  },
  {
    id: 'mock-forum-2',
    title: 'Review: Cursada de Programación I (2024)',
    description: 'Les cuento mi experiencia cursando Programación I este año. Tips para aprobar, qué estudiar y cómo organizarse.',
    category: 'review',
    tags: ['programación', 'sistemas', 'review'],
    upvotes: 42,
    downvotes: 3,
    comment_count: 23,
    is_answered: false,
    status: 'active',
    created_at: '2025-01-16T14:00:00Z',
    view_count: 340,
  },
  {
    id: 'mock-forum-3',
    title: '¿Dónde sacar la libreta universitaria?',
    description: 'Soy ingresante 2025 y no encuentro info sobre dónde tramitar la libreta. ¿Es en Alumnado o en la sede de mi carrera?',
    category: 'question',
    tags: ['ingresantes', 'trámites', 'libreta'],
    upvotes: 8,
    downvotes: 0,
    comment_count: 5,
    is_answered: true,
    status: 'active',
    created_at: '2025-01-21T09:30:00Z',
    view_count: 67,
  },
  {
    id: 'mock-forum-4',
    title: 'Recomendación: Mejor bar para estudiar cerca de la facu',
    description: 'Busco un lugar tranquilo con WiFi bueno para estudiar entre clases. ¿Alguna recomendación por la zona de UNLAR?',
    category: 'recommendation',
    tags: ['recomendación', 'estudio', 'bares'],
    upvotes: 25,
    downvotes: 2,
    comment_count: 14,
    is_answered: false,
    status: 'active',
    created_at: '2025-01-19T17:45:00Z',
    view_count: 198,
  },
];

// ============================================
// Mock Events (Eventos)
// ============================================
export const mockEvents: Partial<Event>[] = [
  {
    id: 'mock-event-1',
    title: 'Hackathon UNLAR 2025',
    description: '48 horas de programación, innovación y premios. Equipos de hasta 4 personas. Inscripción gratuita para estudiantes UNLAR.',
    event_type: 'hackathon',
    start_date: '2025-03-15T09:00:00Z',
    end_date: '2025-03-17T18:00:00Z',
    location: 'Aula Magna - Ciudad Universitaria',
    is_virtual: false,
    max_attendees: 100,
    current_attendees: 67,
    registration_required: true,
    organizer: 'Departamento de Sistemas',
    image_urls: ['https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400'],
    status: 'active',
    created_at: '2025-01-10T12:00:00Z',
    view_count: 234,
  },
  {
    id: 'mock-event-2',
    title: 'Charla: Inteligencia Artificial en la Educación',
    description: 'El Dr. López presenta las últimas tendencias en IA aplicada a la educación universitaria. Entrada libre.',
    event_type: 'talk',
    start_date: '2025-02-20T18:00:00Z',
    end_date: '2025-02-20T20:00:00Z',
    location: 'Salón de Actos - Sede Centro',
    is_virtual: true,
    virtual_link: 'https://meet.google.com/abc-defg-hij',
    max_attendees: null,
    current_attendees: 45,
    registration_required: false,
    organizer: 'Centro de Estudiantes',
    image_urls: ['https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400'],
    status: 'active',
    created_at: '2025-01-12T10:00:00Z',
    view_count: 156,
  },
  {
    id: 'mock-event-3',
    title: 'Torneo Interfacultades de Fútbol 5',
    description: 'Torneo relámpago de fútbol 5. Inscribí a tu equipo representando tu carrera. Premios para los 3 primeros.',
    event_type: 'tournament',
    start_date: '2025-02-28T15:00:00Z',
    end_date: '2025-02-28T21:00:00Z',
    location: 'Cancha sintética - Polideportivo UNLAR',
    is_virtual: false,
    max_attendees: 80,
    current_attendees: 52,
    registration_required: true,
    organizer: 'Secretaría de Bienestar Estudiantil',
    image_urls: ['https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400'],
    status: 'active',
    created_at: '2025-01-14T08:00:00Z',
    view_count: 189,
  },
];

// ============================================
// Mock Lost & Found (Perdidos y Encontrados)
// ============================================
export const mockLostFound: Partial<LostFoundItem>[] = [
  {
    id: 'mock-lost-1',
    title: 'Encontré llaves con llavero de River',
    description: 'Encontré un juego de llaves (3 llaves + control de portón) con un llavero de River Plate en el pasillo del 2do piso.',
    item_type: 'found',
    location_found: 'Facultad de Cs. Exactas - 2do piso',
    date_found: '2025-01-20',
    category: 'keys',
    is_resolved: false,
    image_urls: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400'],
    status: 'active',
    created_at: '2025-01-20T14:00:00Z',
    view_count: 45,
  },
  {
    id: 'mock-lost-2',
    title: 'Perdí mi pendrive Kingston 64GB',
    description: 'Se me cayó un pendrive negro Kingston de 64GB en algún lugar entre el buffet y la biblioteca. Tiene archivos importantes de mi tesis.',
    item_type: 'lost',
    location_found: 'Biblioteca Central / Buffet',
    date_found: '2025-01-19',
    category: 'electronics',
    is_resolved: false,
    image_urls: [],
    status: 'active',
    created_at: '2025-01-19T18:30:00Z',
    view_count: 32,
  },
  {
    id: 'mock-lost-3',
    title: 'Encontré campera negra en Aula 15',
    description: 'Quedó una campera negra de abrigo (marca Columbia) en el Aula 15 después de la clase de las 20hs del miércoles.',
    item_type: 'found',
    location_found: 'Aula 15 - Sede Centro',
    date_found: '2025-01-22',
    category: 'clothing',
    is_resolved: false,
    image_urls: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400'],
    status: 'active',
    created_at: '2025-01-22T21:00:00Z',
    view_count: 28,
  },
];

// ============================================
// Mock Services (Servicios)
// ============================================
export const mockServices: Partial<Service>[] = [
  {
    id: 'mock-service-1',
    title: 'Diseño Gráfico - Logos, Flyers, Presentaciones',
    description: 'Estudiante de Diseño ofrezco servicios de diseño gráfico. Logos desde $15.000, flyers desde $8.000. Portfolio disponible.',
    service_type: 'design',
    price_range: '$8.000 - $30.000',
    availability: 'Lunes a Viernes',
    portfolio_urls: ['https://behance.net/ejemplo'],
    image_urls: ['https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400'],
    status: 'active',
    created_at: '2025-01-17T11:00:00Z',
    view_count: 67,
    favorite_count: 15,
  },
  {
    id: 'mock-service-2',
    title: 'Desarrollo Web - Landing Pages y Apps',
    description: 'Hago páginas web, landing pages y aplicaciones. React, Node.js, bases de datos. Precios accesibles para estudiantes.',
    service_type: 'programming',
    price_range: '$25.000 - $80.000',
    availability: 'Flexible',
    portfolio_urls: ['https://github.com/ejemplo'],
    image_urls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400'],
    status: 'active',
    created_at: '2025-01-15T09:00:00Z',
    view_count: 89,
    favorite_count: 22,
  },
  {
    id: 'mock-service-3',
    title: 'Fotografía para eventos y retratos',
    description: 'Fotógrafa con 3 años de experiencia. Cubro eventos universitarios, retratos para LinkedIn, y sesiones casuales.',
    service_type: 'photography',
    price_range: '$20.000 - $50.000',
    availability: 'Fines de semana',
    portfolio_urls: ['https://instagram.com/ejemplo'],
    image_urls: ['https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=400'],
    status: 'active',
    created_at: '2025-01-18T16:00:00Z',
    view_count: 54,
    favorite_count: 18,
  },
];

// ============================================
// Mock Tutoring (Clases Particulares)
// ============================================
export const mockTutoring: Partial<TutoringListing>[] = [
  {
    id: 'mock-tutoring-1',
    title: 'Clases de Análisis Matemático I y II',
    description: 'Estudiante avanzado de Ingeniería. Explico con paciencia, preparo para parciales y finales. Aprobé ambas con 9.',
    subject: 'Análisis Matemático',
    modality: 'both',
    price_per_hour: 8000,
    experience: '2 años dando clases',
    schedule_availability: 'Tardes de Lunes a Jueves',
    image_urls: ['https://images.unsplash.com/photo-1596496050827-8299e0220de1?w=400'],
    status: 'active',
    created_at: '2025-01-16T13:00:00Z',
    view_count: 78,
    favorite_count: 20,
  },
  {
    id: 'mock-tutoring-2',
    title: 'Inglés para exámenes internacionales',
    description: 'Profesora de Inglés (UNLAR). Preparo para FCE, IELTS y TOEFL. También ayudo con inglés técnico para papers.',
    subject: 'Inglés',
    modality: 'virtual',
    price_per_hour: 10000,
    experience: 'Profesora recibida, 4 años de experiencia',
    schedule_availability: 'Flexible - consultar',
    image_urls: ['https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400'],
    status: 'active',
    created_at: '2025-01-19T10:00:00Z',
    view_count: 45,
    favorite_count: 12,
  },
  {
    id: 'mock-tutoring-3',
    title: 'Programación en Python y Java - Desde cero',
    description: 'Si estás arrancando Programación I o II, te ayudo a entender los conceptos. Ejercicios prácticos y proyectos.',
    subject: 'Programación',
    modality: 'both',
    price_per_hour: 7000,
    experience: '1 año, 15+ alumnos aprobados',
    schedule_availability: 'Mañanas y noches',
    image_urls: ['https://images.unsplash.com/photo-1515879218367-8466d910auj7?w=400'],
    status: 'active',
    created_at: '2025-01-20T08:00:00Z',
    view_count: 92,
    favorite_count: 25,
  },
];

// ============================================
// Mock Announcements (Anuncios)
// ============================================
export const mockAnnouncements: Partial<Announcement>[] = [
  {
    id: 'mock-announcement-1',
    title: 'Inscripción a materias - 2do cuatrimestre 2025',
    description: 'Se informa que la inscripción a materias del 2do cuatrimestre estará habilitada del 1 al 15 de julio a través del SIU Guaraní.',
    priority: 'important',
    source: 'faculty',
    target_careers: [],
    expires_at: '2025-07-15T23:59:00Z',
    image_urls: [],
    status: 'active',
    created_at: '2025-01-22T08:00:00Z',
    view_count: 456,
  },
  {
    id: 'mock-announcement-2',
    title: 'Becas de transporte - Convocatoria abierta',
    description: 'El Centro de Estudiantes informa que están abiertas las becas de transporte para estudiantes del interior. Presentar documentación en Bienestar.',
    priority: 'normal',
    source: 'student_center',
    target_careers: [],
    expires_at: '2025-02-28T23:59:00Z',
    image_urls: [],
    status: 'active',
    created_at: '2025-01-21T10:00:00Z',
    view_count: 234,
  },
];
